class Numeric
  def measure: -> Measure
  def newton:  -> Newton
  def newtons: -> Newton
  def radian:  -> Radian
  def radians: -> Radian
end

class String
  def pluralize: -> String
  def singularize: -> String
  def underscore: -> String
end

class Measure
  attr_reader value: Numeric
  def initialize: (Numeric | Measure) -> void
  def +: (Measure) -> Measure
  def ==: (Measure) -> bool
  def *: (Numeric) -> Measure
  def to_s: -> String
  def underscored_class: -> String
  def self.allow_numeric_convert: -> untyped
end

class Newton < Measure
end

class Radian < Measure
end
